apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-regulator-statefulset
spec:
  serviceName: "kafka-regulator"
  replicas: 1
  selector:
    matchLabels:
      app: kafka-regulator
  template:
    metadata:
      labels:
        app: kafka-regulator
    spec:
      containers:
      - name: kafka-regulator
        image: windmuse.iptime.org:8084/repository/kafka-regulator:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8089
